USE NovelWebsite
GO
IF OBJECT_ID('AUTHOR','U') IS NOT NULL--U用户自定义表
  DROP TABLE AUTHOR
GO
CREATE TABLE AUTHOR
(
AuthorID CHAR(10) NOT NULL,
Points MONEY NOT NULL DEFAULT 0,
AuthorPassWord VARCHAR(16) NOT NULL,
CONSTRAINT AuthorPK PRIMARY KEY(AuthorID)
);
GO
--TEST
--SELECT * FROM AUTHOR
