USE NovelWebsite
GO 
IF OBJECT_ID('COLLECTIONS','U') IS NOT NULL--U用户自定义表
  DROP TABLE COLLECTIONS
GO
CREATE TABLE COLLECTIONS
(
NovelID INT NOT NULL IDENTITY(1,1),--PK1,FK1
ReaderID CHAR(10) NOT NULL,
CONSTRAINT CollectionPK PRIMARY KEY(NovelID,ReaderID),
CONSTRAINT NovelFK FOREIGN KEY(NovelID)
           REFERENCES NOVEL(NovelID)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION,
CONSTRAINT ReaderFK FOREIGN KEY(ReaderID)
           REFERENCES READER(ReaderID)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION
);
--TEST
--SELECT * FROM COLLECTION