USE NovelWebsite
GO
IF OBJECT_ID('EDITOR','U') IS NOT NULL
  DROP TABLE EDITOR
GO
CREATE TABLE EDITOR
(
EditorID CHAR(10)NOT NULL,
HireDate DATE NOT NULL,
FireDate DATE NULL,
Salary MONEY NOT NULL DEFAULT(5000),
CONSTRAINT EditorPK PRIMARY KEY(EditorID)
);
--TEST
--SELECT * FROM EDITOR