USE NovelWebsite
GO
IF OBJECT_ID('IN_CHARGE_OF','U') IS NOT NULL--U用户自定义表
  DROP TABLE IN_CHARGE_OF
GO
CREATE TABLE IN_CHARGE_OF
(
EditorID CHAR(10) NOT NULL,
AuthorID CHAR(10) NOT NULL,
CONSTRAINT ICOPK PRIMARY KEY(EditorID,AuthorID),
CONSTRAINT EditorFK FOREIGN KEY(EditorID)
           REFERENCES EDITOR(EditorID)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION,
CONSTRAINT AuthorFK1 FOREIGN KEY(AuthorID)
           REFERENCES AUTHOR(AuthorID)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION
);
GO
--TEST
---SELECT * FROM IN_CHARGE_OF