USE NovelWebsite
GO
IF OBJECT_ID('READER','U') IS NOT NULL--U用户自定义表
  DROP TABLE READER
GO
CREATE TABLE READER
(
ReaderID CHAR(10) NOT NULL,
Points MONEY NOT NULL DEFAULT 0,
ReaderPassWord VARCHAR(16) NOT NULL,
CONSTRAINT ReaderPK PRIMARY KEY (ReaderID)
);
--TEST
SELECT * FROM READER