USE NovelWebsite
GO
IF OBJECT_ID('SUBSCRIBE','U') IS NOT NULL
  DROP TABLE SUBSCRIBE
GO
CREATE TABLE SUBSCRIBE
(
ReaderID CHAR(10) NOT NULL,
NovelID INT NOT NULL IDENTITY(1,1),
ChapterNum VARCHAR(5) NOT NULL,
Price MONEY NOT NULL DEFAULT (5),--每章节单价
CONSTRAINT SubscribePK PRIMARY KEY(ReaderID,NovelID,ChapterNum),
CONSTRAINT ReaderFK1 FOREIGN KEY(ReaderID)
           REFERENCES READER(ReaderID)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION,
CONSTRAINT ChapterFKs FOREIGN KEY(NovelID,ChapterNum)--组合主键不能用做单一外键引用
           REFERENCES CHAPTER(NovelID,ChapterNum)
		           ON UPDATE NO ACTION 
				   ON DELETE NO ACTION
);
GO
--TEST
--SELECT * FROM SUBSCRIBE